package com.taiji.cc.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.taiji.cc.order.data.bean.Order;
import com.taiji.cc.order.data.bean.OrderList;
import com.taiji.cc.patient.data.Patient;

import com.taiji.cc.greendao.db.OrderDao;
import com.taiji.cc.greendao.db.OrderListDao;
import com.taiji.cc.greendao.db.PatientDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig orderDaoConfig;
    private final DaoConfig orderListDaoConfig;
    private final DaoConfig patientDaoConfig;

    private final OrderDao orderDao;
    private final OrderListDao orderListDao;
    private final PatientDao patientDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        orderDaoConfig = daoConfigMap.get(OrderDao.class).clone();
        orderDaoConfig.initIdentityScope(type);

        orderListDaoConfig = daoConfigMap.get(OrderListDao.class).clone();
        orderListDaoConfig.initIdentityScope(type);

        patientDaoConfig = daoConfigMap.get(PatientDao.class).clone();
        patientDaoConfig.initIdentityScope(type);

        orderDao = new OrderDao(orderDaoConfig, this);
        orderListDao = new OrderListDao(orderListDaoConfig, this);
        patientDao = new PatientDao(patientDaoConfig, this);

        registerDao(Order.class, orderDao);
        registerDao(OrderList.class, orderListDao);
        registerDao(Patient.class, patientDao);
    }
    
    public void clear() {
        orderDaoConfig.clearIdentityScope();
        orderListDaoConfig.clearIdentityScope();
        patientDaoConfig.clearIdentityScope();
    }

    public OrderDao getOrderDao() {
        return orderDao;
    }

    public OrderListDao getOrderListDao() {
        return orderListDao;
    }

    public PatientDao getPatientDao() {
        return patientDao;
    }

}
