package com.taiji.app.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import com.taiji.app.greendao.bean.Test;
import com.taiji.app.greendao.bean.Report;

import com.taiji.app.greendao.db.TestDao;
import com.taiji.app.greendao.db.ReportDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig testDaoConfig;
    private final DaoConfig reportDaoConfig;

    private final TestDao testDao;
    private final ReportDao reportDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        testDaoConfig = daoConfigMap.get(TestDao.class).clone();
        testDaoConfig.initIdentityScope(type);

        reportDaoConfig = daoConfigMap.get(ReportDao.class).clone();
        reportDaoConfig.initIdentityScope(type);

        testDao = new TestDao(testDaoConfig, this);
        reportDao = new ReportDao(reportDaoConfig, this);

        registerDao(Test.class, testDao);
        registerDao(Report.class, reportDao);
    }
    
    public void clear() {
        testDaoConfig.getIdentityScope().clear();
        reportDaoConfig.getIdentityScope().clear();
    }

    public TestDao getTestDao() {
        return testDao;
    }

    public ReportDao getReportDao() {
        return reportDao;
    }

}
